version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mysql"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./resources/script/init.sql:/docker-entrypoint-initdb.d/init.sql